name: CI_WEIS

# We run CI on push commits on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"] #, "macOS-latest"]
        python-version: ["3.8"]
        
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true
          python-version: 3.8
          environment-file: environment.yml
      
      # Install dependencies of WEIS specific to ubuntu
      - name: Add dependencies ubuntu specific
        if: false == contains( matrix.os, 'windows')
        shell: pwsh # putting in a shell command makes for compile linking problems later
        # (if you use the shell here, cannot use 'compiler' package, but mpi only seems to work with it)
        run: |
          conda install -y petsc4py mpi4py openmpi==4.0.5
          python -c "import platform; print(platform.node())"

      # Install dependencies of WISDEM specific to windows
      - name: Add dependencies windows specific
        if: contains( matrix.os, 'windows')
        run: |
          conda install -y m2w64-toolchain libpython

      # Debugging session
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
        
      # Install WISDEM
      - name: Install WEIS
        shell: pwsh
        run: |
          python setup.py develop
          
      # List the collected tests for debugging purposes
      - name: List tests
        shell: pwsh
        run: |
          pytest weis --collect-only
        
      # Run all tests within WEIS, but not computationally expensive examples
      - name: Run tests within WEIS
        shell: pwsh
        run: |
          pytest weis --cov-config=.coverageac --cov=weis
      
      # Run coveralls
      - name: Run coveralls
        if: contains( matrix.os, 'ubuntu')
        # This also works, https://github.com/AndreMiras/coveralls-python-action
        #uses: AndreMiras/coveralls-python-action@develop
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github